name: salutation sur un jour quelconque

on: workflow_dispatch

env:
  DAY_OF_WEEK: Lundi ## Variable d'environnement pour l'ensemble du flux de travail

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Salut ## Variable d'environnement pour la tâche
    steps:
        with: # Set the secret as an input
          var_sec2: ${{ VAR_SEC2 }}
        env: # Or as an environment variable
          var_sec: ${{ VAR_SEC }}


      - name: "Dites Salut Mona nous sommes lundi"
        run: echo "$Greeting $First_Name. Nous sommes $DAY_OF_WEEK! La val de VAR_SEC est $var_sec et la valeur de VAR_SEC2 est $var_sec2"
        env:
          First_Name: Mona ## Variable d'environnement uniquement pour l'étape "Dites Salut Mona nous sommes lundi" de la tâche "greeting_job"
